import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-cyan-500 to-blue-500`}
      >
        <header className="py-10">
          <h1 className="text-3xl font-bold text-white text-center">Тестовое задание Emfy</h1>
        </header>
          {children}
        <footer className="py-20">
          <p className="text-center text-semibold opacity-60 text-white">&#169; Artemy Kalugin, { new Date().getFullYear() }</p>
        </footer>
      </body>
    </html>
  );
}
